# This is a utility file to test the ShowIt docker image locally
# docker-compose --env-file=.env.docker-compose up

version: "3.9"
services:
  showit:
    env_file:
      - .env.docker-compose
    build:
      context: .
    ports:
      - "1234:80"
