server {
    listen   80;
    listen   [::]:80 default ipv6only=on;

    server_tokens off;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    add_header Content-Security-Policy "default-src 'self' 'unsafe-inline'" always;

    location ~ /assets/(.+)$ {
        root   /usr/share/nginx/html;
        try_files $uri /assets/$1;
    }

    location ~ .(config.js)$ {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /$1;
    }

    location ~ .(manifest.json)$ {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /$1;
    }

    location ~ .(favicon.png)$ {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /$1;
    }

    location ~ .(locales/(.+)/translation.json)$ {
            root   /usr/share/nginx/html;
            try_files $uri $uri/ /$1;
        }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html =404;
    }
}
